# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hellorails_development
  host: localhost
  username: postgres
  password: '24434'

 
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: hellorails_test
  host: localhost
  username: postgres
  password: '24434'

production:
  <<: *default
  database: hellorails_production
  username: postgres
  password: <%= ENV["HELLORAILS_DATABASE_PASSWORD"] %>
